/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import org.apache.*;
import BUS_Run.ThongKeChung;
import BUS_Run.ThongKeGiua2Ngay;
import BUS_Run.ThongKeTheoThang;
import DAO.QueryDB_ThongKe;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author thaiv
 */
public class FormThongKe extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel(0,0);
    /**
     * Creates new form ThongKe
     */
    public FormThongKe() {
        initComponents();
        jLabel1.setVisible(false);
        tongTienLabel.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        thongKeTable = new javax.swing.JTable();
        thongKeChungButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        thangComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tongTienLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thongKeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(thongKeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 787, 370));

        thongKeChungButton.setText("Thống kê chung");
        thongKeChungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongKeChungButtonActionPerformed(evt);
            }
        });
        jPanel1.add(thongKeChungButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 181, -1));

        jButton1.setText("Thống kê bán hàng theo tháng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton2.setText("Thống kê những");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 181, -1));

        thangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        jPanel1.add(thangComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel1.setText("Tổng doanh thu:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, -1, -1));

        tongTienLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tongTienLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tongTienLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 164, -1));

        jLabel2.setText("Từ ngày");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel3.setText("Đến ngày");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 100, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("THỐNG KÊ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 10));

        jButton3.setText("EXPORT EXCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thongKeChungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongKeChungButtonActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        tongTienLabel.setVisible(false);
        ThongKeChung TKC = new ThongKeChung();
        thongKeTable.setModel(TKC.thongKe());
    }//GEN-LAST:event_thongKeChungButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handlig code here:
        jLabel1.setVisible(true);
        tongTienLabel.setVisible(true);
        String thang = thangComboBox.getSelectedItem().toString();
        int month=0;
        String tongtien="";
        switch (thang)
        {
            case "Tháng 1":
                month=1;
                break;
            case "Tháng 2":
                month=2;
                break;
            case "Tháng 3":
                month=3;
                break;
            case "Tháng 4":
                month=4;
                break;
            case "Tháng 5":
                month=5;
                break;
            case "Tháng 6":
                month=6;
                break;
            case "Tháng 7":
                month=7;
                break;
            case "Tháng 8":
                month=8;
                break;
            case "Tháng 9":
                month=9;
                break;
            case "Tháng 10":
                month=10;
                break;
            case "Tháng 11":
                month=11;
                break;
            case "Tháng 12":
                month=12;
                break;
        }
        ThongKeTheoThang TKTT = new ThongKeTheoThang();
        try {
            thongKeTable.setModel(TKTT.buildTableModel(month));
        } catch (SQLException ex) {
            Logger.getLogger(ThongKeChung.class.getName()).log(Level.SEVERE, null, ex);
        }
        int tong=0;
        for (int i=0;i<thongKeTable.getRowCount();i++)
        {
            tong+= Integer.parseInt(thongKeTable.getValueAt(i,4)+"");
        }
        tongtien = Integer.toString(tong);
        tongTienLabel.setText(tongtien);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        tongTienLabel.setVisible(true);
        String tongtien="";
        String ngaybd = jTextField1.getText();
        String ngaykt = jTextField2.getText();
        ThongKeGiua2Ngay TKG2N = new ThongKeGiua2Ngay();
        try {
            thongKeTable.setModel(TKG2N.buildTableModel(ngaybd, ngaykt));
        } catch (SQLException ex) {
            Logger.getLogger(ThongKeChung.class.getName()).log(Level.SEVERE, null, ex);
        }
        int tong=0;
        for (int i=0;i<thongKeTable.getRowCount();i++)
        {
            tong+= Integer.parseInt(thongKeTable.getValueAt(i,4)+"");
        }
        tongtien = Integer.toString(tong);
        tongTienLabel.setText(tongtien);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet ws = wb.createSheet("Thống kê");
        Row HeaderRow = ws.createRow(0);
        
        TableModel tbmodel = thongKeTable.getModel();
        
        for (int i=0; i<tbmodel.getColumnCount(); i++)
        {
            HeaderRow.createCell(i).setCellValue(tbmodel.getColumnName(i));
        }
        
        Row rows = ws.createRow(1);
        for (int j=0; j<tbmodel.getRowCount(); j++)
        {
            for (int k=0; k<tbmodel.getColumnCount(); k++)
            {
                rows.createCell(k).setCellValue(tbmodel.getValueAt(j,k).toString());
            }
            rows = ws.createRow((j + 2));
        }
        
        
        try {
            wb.write(new FileOutputStream("thongke.xlsx"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormThongKe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Desktop dt = Desktop.getDesktop();
        try 
        {
            dt.open(new File("thongke.xlsx"));
        } catch (IOException ex) {
            Logger.getLogger(FormThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> thangComboBox;
    private javax.swing.JButton thongKeChungButton;
    private javax.swing.JTable thongKeTable;
    private javax.swing.JLabel tongTienLabel;
    // End of variables declaration//GEN-END:variables
}
