/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;


import BUS_OPP_Class.KhachHang;
import BUS_OPP_RUN.RunKhachHang;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaiv
 */
public class TimKiemNangCaoKH extends javax.swing.JFrame {

    /**
     * Creates new form TimKiemNangCaoKH
     */
    public RunKhachHang TK = new RunKhachHang();
    
    public int HTtrave=-1;
    
    public void setHTtrave(int i)
    {
        this.HTtrave=i;
    }
    
    public int getHTtrave()
    {
        return HTtrave;
    }
    
    
    public TimKiemNangCaoKH() {
        initComponents();
        DefaultTableModel modeltable;
        TimKiemNCKH.setModel(TK.ReadKH());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LCTKNCKH = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CMND = new javax.swing.JTextField();
        TenKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TimKiemNCKH = new javax.swing.JTable();
        AND = new javax.swing.JRadioButton();
        OR = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tên KH");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 10));

        jLabel1.setText("CMND");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        CMND.setForeground(new java.awt.Color(255, 255, 255));
        CMND.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 270, 20));

        TenKH.setForeground(new java.awt.Color(255, 255, 255));
        TenKH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 270, 20));

        TimKiemNCKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TimKiemNCKH);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 530, 140));

        LCTKNCKH.add(AND);
        AND.setSelected(true);
        AND.setText("AND");
        jPanel2.add(AND, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        LCTKNCKH.add(OR);
        OR.setText("OR");
        jPanel2.add(OR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel4.setText("SDT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 10));

        SDT.setForeground(new java.awt.Color(255, 255, 255));
        SDT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        HTtrave=-1;
    }//GEN-LAST:event_jButton1ActionPerformed

    public ArrayList TraGiaTri()
    {
        int n = TimKiemNCKH.getRowCount();
        ArrayList<KhachHang> KH = new ArrayList<KhachHang>();
        for(int i=0; i<n; i++)
        {
            KhachHang kh = new KhachHang();
            kh.setCMND(TimKiemNCKH.getModel().getValueAt(i, 0).toString());
            kh.setTenKH(TimKiemNCKH.getModel().getValueAt(i, 1).toString());
            kh.setSDT(TimKiemNCKH.getModel().getValueAt(i, 2).toString());
            kh.setDiaChi(TimKiemNCKH.getModel().getValueAt(i, 3).toString());
            KH.add(kh);
        }
        return KH;
    }
    
    public void TraVeHT0()
    {
        ArrayList<KhachHang> KH = TraGiaTri();
        DefaultTableModel modeltable = null;
        FramesTable FT = new FramesTable();
        modeltable = FT.khungtableKH(KH);
        Menu.modelTKNC= modeltable;
        Menu.XuatGTTimKiemNCKH();
    }
    
    public void TraVeHT1()
    {
        int i = TimKiemNCKH.getSelectedRow();
        if(i!=-1)
        {
            String ma = TimKiemNCKH.getModel().getValueAt(i,0).toString();
            String ten = TimKiemNCKH.getModel().getValueAt(i,1).toString();
            String sdt = TimKiemNCKH.getModel().getValueAt(i,2).toString();
            String diachi = TimKiemNCKH.getModel().getValueAt(i,3).toString();
            Menu.xuatdulieuKH(ma, ten, sdt, diachi);
        }
        else JOptionPane.showInternalMessageDialog(null,"Chưa chọn đối tượng !");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        switch(getHTtrave())
        {
            case 0: TraVeHT0(); break;
            case 1: TraVeHT1();break;
            default: break;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void XuatBangTimKiem(DefaultTableModel modeltable)
    {
        TimKiemNCKH.setModel(modeltable);
        if(modeltable.getRowCount()==0) JOptionPane.showInternalMessageDialog(null,"Kết quả tìm kiếm không có !");
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String CM ="";
        CM = CMND.getText();
        String Ten ="";
        Ten = TenKH.getText();
        String SoDT ="";
        SoDT = SDT.getText();
        DefaultTableModel modeltable = null;
        if(AND.isSelected())
        {
            modeltable=TK.TK_And(CM, Ten, SoDT);
            XuatBangTimKiem(modeltable);
        }
        else
        {
            if(OR.isSelected()) 
            {
                modeltable=TK.TK_Or(CM, Ten, SoDT);
                XuatBangTimKiem(modeltable);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AND;
    private javax.swing.JTextField CMND;
    private javax.swing.ButtonGroup LCTKNCKH;
    private javax.swing.JRadioButton OR;
    private javax.swing.JTextField SDT;
    private javax.swing.JTextField TenKH;
    private javax.swing.JTable TimKiemNCKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
