/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import BUS_OPP_Class.CTHoaDon;
import BUS_OPP_Class.CTPhieuNhap;
import BUS_OPP_Class.KhachHang;
import BUS_OPP_Class.NhaCC;
import BUS_OPP_Class.NhanVien;
import BUS_OPP_RUN.ArrayListALL;
import BUS_OPP_RUN.RunCTHoaDon;
import BUS_OPP_RUN.RunCTPhieuNhap;
import BUS_OPP_RUN.RunCungCap;
import BUS_OPP_RUN.RunHoaDon;
import BUS_OPP_RUN.RunKhachHang;
import BUS_OPP_RUN.RunNhanVien;
import BUS_OPP_RUN.RunPhieuNhap;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.JMarsDarkTheme;

/**
 *
 * @author thaiv
 */
public class XemLaiPhieu extends javax.swing.JFrame {

    public FramesTable FT = new FramesTable();
    /**
     * Creates new form XemLaiPhieu
     */
    public XemLaiPhieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPhieu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLHoaDonMaHD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLHoaDonMaNV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLHoaDonMaKH = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLHoaDonTenNV = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLHoaDonTenKH = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLHoaDonNgay = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLHoaDonMaSP = new javax.swing.JLabel();
        jBXoa1SPTrongHD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCTHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePhieuNhap = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLPhieuNhapMaP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLPhieuNhapMaNV = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLPhieuNhapMaCC = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLPhieuNhapTenNV = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLPhieuNhapTenCC = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLPhieuNhapNgay = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLPhieuNhapMaSP = new javax.swing.JLabel();
        jBXoa1SPTrongHD1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCTPhieuNhap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MenuPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPhieuMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLHoaDonMaHD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonMaHD.setText("Mã Hóa Đơn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Mã Khách Hàng:");

        jLHoaDonMaNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonMaNV.setText("Mã Nhân Viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Mã Nhân Viên:");

        jLHoaDonMaKH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonMaKH.setText("Mã Khách Hàng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Tên Nhân Viên:");

        jLHoaDonTenNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonTenNV.setText("Tên Nhân Viên");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Tên Khách Hàng:");

        jLHoaDonTenKH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonTenKH.setText("Tên Khách Hàng");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Ngày:");

        jLHoaDonNgay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonNgay.setText("Ngày");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Mã sản phẩm:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Chi tiết hóa đơn:");

        jLHoaDonMaSP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLHoaDonMaSP.setText("Mã sản phẩm");

        jBXoa1SPTrongHD.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jBXoa1SPTrongHD.setText("Xóa sản phẩm này trong hóa đơn này");
        jBXoa1SPTrongHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoa1SPTrongHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(jLHoaDonMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(jLHoaDonMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLHoaDonNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHoaDonTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLHoaDonMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLHoaDonMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLHoaDonTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBXoa1SPTrongHD)
                                    .addComponent(jLabel7))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHoaDonMaHD)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLHoaDonNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHoaDonMaNV)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLHoaDonTenNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLHoaDonMaKH)
                    .addComponent(jLabel9)
                    .addComponent(jLHoaDonTenKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBXoa1SPTrongHD)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLHoaDonMaSP)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHoaDon);

        jTableCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCTHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCTHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCTHoaDon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        MenuPhieu.addTab("Hóa Đơn\n", jPanel1);

        jTablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePhieuNhap);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLPhieuNhapMaP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapMaP.setText("Mã Phiếu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Mã phiếu nhập:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Mã cung cấp:");

        jLPhieuNhapMaNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapMaNV.setText("Mã Nhân Viên");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Mã Nhân Viên:");

        jLPhieuNhapMaCC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapMaCC.setText("Mã cung cấp");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Tên Nhân Viên:");

        jLPhieuNhapTenNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapTenNV.setText("Tên Nhân Viên");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Tên cung cấp:");

        jLPhieuNhapTenCC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapTenCC.setText("Tên cung cấp");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Ngày:");

        jLPhieuNhapNgay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapNgay.setText("Ngày");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Mã sản phẩm:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Chi tiết hóa đơn:");

        jLPhieuNhapMaSP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPhieuNhapMaSP.setText("Mã sản phẩm");

        jBXoa1SPTrongHD1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jBXoa1SPTrongHD1.setText("Xóa sản phẩm này trong hóa đơn này");
        jBXoa1SPTrongHD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBXoa1SPTrongHD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLPhieuNhapMaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(382, 382, 382))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(34, 34, 34)
                                .addComponent(jLPhieuNhapMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jBXoa1SPTrongHD1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLPhieuNhapMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPhieuNhapMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPhieuNhapNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPhieuNhapTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPhieuNhapTenCC, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPhieuNhapMaP)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(jLPhieuNhapNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPhieuNhapMaNV)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLPhieuNhapTenNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLPhieuNhapMaCC)
                    .addComponent(jLabel12)
                    .addComponent(jLPhieuNhapTenCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBXoa1SPTrongHD1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLPhieuNhapMaSP)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTableCTPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCTPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCTPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCTPhieuNhap);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );

        MenuPhieu.addTab("Phiếu Nhập\n", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPhieu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPhieu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPhieuMouseClicked
        // TODO add your handling code here:
        int i = MenuPhieu.getSelectedIndex();
        if(i!=-1) luachon(i);
    }//GEN-LAST:event_MenuPhieuMouseClicked

    private void jTableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHoaDonMouseClicked
        // TODO add your handling code here:
        int sel = jTableHoaDon.getSelectedRow();
        if(sel!=-1)
        {
            String mahd = jTableHoaDon.getModel().getValueAt(sel,0).toString();
            jLHoaDonMaHD.setText(mahd);
            String manv = jTableHoaDon.getModel().getValueAt(sel,1).toString();
            String makh = jTableHoaDon.getModel().getValueAt(sel,2).toString();
            String Ngay = jTableHoaDon.getModel().getValueAt(sel,3).toString();
            jLHoaDonNgay.setText(Ngay);
            RunNhanVien rnv = new RunNhanVien();
            NhanVien nv = new NhanVien();
            nv=rnv.timkiem1NV(manv);
            jLHoaDonMaNV.setText(nv.getMaNV());
            jLHoaDonTenNV.setText(nv.getTenNV());
            RunKhachHang rkh = new RunKhachHang();
            KhachHang kh = new KhachHang();
            kh = rkh.timkhachhang(makh);
            jLHoaDonMaKH.setText(kh.getCMND());
            jLHoaDonTenKH.setText(kh.getTenKH());
            jTableCTHoaDon.removeAll();
            jTableCTHoaDon.setModel(FT.khungtableCTHDonBanHang());
            for(CTHoaDon cthd : ArrayListALL.ListCTHD)
            {
                if(mahd.equals(cthd.getMaP()))
                {
                    DefaultTableModel model = new DefaultTableModel();
                    model = (DefaultTableModel) jTableCTHoaDon.getModel();
                    Vector row = new Vector();
                    row.add(cthd.getMaSP());
                    row.add(cthd.getMaKM());
                    row.add(cthd.getSL());
                    row.add(cthd.getTTien());
                    model.addRow(row);
                    jTableCTHoaDon.setModel(model);
                }
            }
        }
    }//GEN-LAST:event_jTableHoaDonMouseClicked

    private void jTableCTHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCTHoaDonMouseClicked
        // TODO add your handling code here:
        int sel = jTableCTHoaDon.getSelectedRow();
        if(sel != -1)
        {
            String masp = jTableCTHoaDon.getModel().getValueAt(sel,0).toString();
            jLHoaDonMaSP.setText(masp);
        }
    }//GEN-LAST:event_jTableCTHoaDonMouseClicked

    private void jBXoa1SPTrongHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoa1SPTrongHDActionPerformed
        // TODO add your handling code here:
        int sel = jTableCTHoaDon.getSelectedRow();
        if(sel != -1)
        {
            String masp = jTableCTHoaDon.getModel().getValueAt(sel,0).toString();
            jLHoaDonMaSP.setText(masp);
            String mahd = jLHoaDonMaHD.getText();
            RunCTHoaDon rhd = new RunCTHoaDon();
            rhd.Del1SPTrongHD(mahd, masp);
            jTableCTHoaDon.remove(sel);
        }
    }//GEN-LAST:event_jBXoa1SPTrongHDActionPerformed

    private void jTablePhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePhieuNhapMouseClicked
        // TODO add your handling code here:
        int sel = jTablePhieuNhap.getSelectedRow();
        if(sel!=-1)
        {
            String mapn = jTablePhieuNhap.getModel().getValueAt(sel,0).toString();
            jLPhieuNhapMaP.setText(mapn);
            String manv = jTablePhieuNhap.getModel().getValueAt(sel,1).toString();
            String macc = jTablePhieuNhap.getModel().getValueAt(sel,2).toString();
            String Ngay = jTablePhieuNhap.getModel().getValueAt(sel,3).toString();
            jLPhieuNhapNgay.setText(Ngay);
            RunNhanVien rnv = new RunNhanVien();
            NhanVien nv = new NhanVien();
            nv=rnv.timkiem1NV(manv);
            jLPhieuNhapMaNV.setText(nv.getMaNV());
            jLPhieuNhapTenNV.setText(nv.getTenNV());
            RunCungCap rcc = new RunCungCap();
            NhaCC cc = new NhaCC();
            cc = rcc.XuatNhaCC(macc);
            jLPhieuNhapMaCC.setText(cc.getMaCC());
            jLPhieuNhapTenCC.setText(cc.getTenNCC());
            jTableCTPhieuNhap.removeAll();
            jTableCTPhieuNhap.setModel(FT.khungtableCTPhieuNhap());
            for(CTPhieuNhap ctpn : ArrayListALL.ListCTPN)
            {
                if(mapn.equals(ctpn.getMaP()))
                {
                    DefaultTableModel model = new DefaultTableModel();
                    model = (DefaultTableModel) jTableCTPhieuNhap.getModel();
                    Vector row = new Vector();
                    row.add(ctpn.getMaSP());
                    row.add(ctpn.getSL());
                    row.add(ctpn.getTTien());
                    model.addRow(row);
                    jTableCTPhieuNhap.setModel(model);
                }
            }
        }
    }//GEN-LAST:event_jTablePhieuNhapMouseClicked

    private void jBXoa1SPTrongHD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBXoa1SPTrongHD1ActionPerformed
        // TODO add your handling code here:
        int sel = jTableCTPhieuNhap.getSelectedRow();
        if(sel != -1)
        {
            String masp = jTableCTPhieuNhap.getModel().getValueAt(sel,0).toString();
            jLPhieuNhapMaSP.setText(masp);
            String mapn = jLPhieuNhapMaP.getText();
            RunCTPhieuNhap rpn = new RunCTPhieuNhap();
            rpn.Del1SPTrongPN(mapn, masp);
            jTableCTPhieuNhap.remove(sel);
        }
    }//GEN-LAST:event_jBXoa1SPTrongHD1ActionPerformed

    private void jTableCTPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCTPhieuNhapMouseClicked
        // TODO add your handling code here:
        int sel = jTableCTPhieuNhap.getSelectedRow();
        if(sel != -1)
        {
            String masp = jTableCTPhieuNhap.getModel().getValueAt(sel,0).toString();
            jLPhieuNhapMaSP.setText(masp);
        }
    }//GEN-LAST:event_jTableCTPhieuNhapMouseClicked

    public void luachon(int i)
    {
        switch(i)
        {
            case 0: xuatHoaDon();break;
            case 1: xuatPhieuNhap();break;
            default: break;
        }
    }
    
    public void xuatHoaDon()
    {
        RunHoaDon hd = new RunHoaDon();
        jTableHoaDon.setModel(hd.ReadHD());
        jTableCTHoaDon.setModel(FT.khungtableCTHDonBanHang());
    }
    
    public void xuatPhieuNhap()
    {
        RunPhieuNhap pn = new RunPhieuNhap();
        jTablePhieuNhap.setModel(pn.ReadPN());
        jTableCTPhieuNhap.setModel(FT.khungtableCTPhieuNhap());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemLaiPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemLaiPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemLaiPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemLaiPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
			UIManager.setLookAndFeel (new MaterialLookAndFeel ());
		}
		catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace ();
                        
		}
        if (UIManager.getLookAndFeel() instanceof MaterialLookAndFeel) {
            MaterialLookAndFeel.changeTheme(new JMarsDarkTheme());
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemLaiPhieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MenuPhieu;
    private javax.swing.JButton jBXoa1SPTrongHD;
    private javax.swing.JButton jBXoa1SPTrongHD1;
    private javax.swing.JLabel jLHoaDonMaHD;
    private javax.swing.JLabel jLHoaDonMaKH;
    private javax.swing.JLabel jLHoaDonMaNV;
    private javax.swing.JLabel jLHoaDonMaSP;
    private javax.swing.JLabel jLHoaDonNgay;
    private javax.swing.JLabel jLHoaDonTenKH;
    private javax.swing.JLabel jLHoaDonTenNV;
    private javax.swing.JLabel jLPhieuNhapMaCC;
    private javax.swing.JLabel jLPhieuNhapMaNV;
    private javax.swing.JLabel jLPhieuNhapMaP;
    private javax.swing.JLabel jLPhieuNhapMaSP;
    private javax.swing.JLabel jLPhieuNhapNgay;
    private javax.swing.JLabel jLPhieuNhapTenCC;
    private javax.swing.JLabel jLPhieuNhapTenNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCTHoaDon;
    private javax.swing.JTable jTableCTPhieuNhap;
    private javax.swing.JTable jTableHoaDon;
    private javax.swing.JTable jTablePhieuNhap;
    // End of variables declaration//GEN-END:variables
}
